services:
  mysql:
    image: mysql:8.0
    container_name: simas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_USER: simas
      MYSQL_PASSWORD: simas123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - simas_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simas_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - simas_network

volumes:
  mysql_data:

networks:
  simas_network:
    driver: bridge