services:
  app:
    image: php:8.1-apache
    container_name: simas_app
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
    depends_on:
      - mysql
    networks:
      - simas_network
    command: >
      bash -c "apt-get update && apt-get install -y libzip-dev zip libpng-dev libonig-dev libxml2-dev &&
      docker-php-ext-install pdo_mysql mysqli mbstring zip gd intl &&
      a2enmod rewrite &&
      echo '<VirtualHost *:80>
        DocumentRoot /var/www/html/public
        <Directory /var/www/html/public>
          AllowOverride All
          Require all granted
        </Directory>
      </VirtualHost>' > /etc/apache2/sites-available/000-default.conf &&
      chmod -R 777 /var/www/html/writable &&
      mkdir -p /var/www/html/writable/session &&
      chmod -R 777 /var/www/html/writable/session &&
      apache2-foreground"

  mysql:
    image: mysql:8.0
    container_name: simas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ci4
      MYSQL_USER: simas
      MYSQL_PASSWORD: simas123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - simas_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: simas_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - simas_network

volumes:
  mysql_data:

networks:
  simas_network:
    driver: bridge